import { ICatObject } from 'types/types';

export const catsData: Array<ICatObject> = [
  {
    id: 1,
    breed: 'Maine-coon',
    homeCity: 'Minsk',
    name: 'Felix',
    imageSrc: 'https://klike.net/uploads/posts/2023-01/1674113220_3-76.jpg',
    price: 600,
  },
  {
    id: 2,
    breed: 'Maine-coon',
    homeCity: 'Vitebsk',
    name: 'Monya',
    imageSrc:
      'https://prohvost.club/wp-content/uploads/2018/03/mramornyy-meyn-kun-s-ugryumym-vzglyadom-na-chernom-fone.jpg',
    price: 700,
  },
  {
    id: 3,
    breed: 'Abyssinian',
    homeCity: 'Gomel',
    name: 'Tutsi',
    imageSrc:
      'https://skstoit.ru/wp-content/uploads/2022/01/skolko-stoit-abissinskaya-koshka-1.jpg',
    price: 400,
  },
  {
    id: 4,
    breed: 'Abyssinian',
    homeCity: 'Grodno',
    name: 'Markiz',
    imageSrc: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Valentino.jpg',
    price: 500,
  },
  {
    id: 5,
    breed: 'American bobtail',
    homeCity: 'Grodno',
    name: 'Liza',
    imageSrc:
      'https://chudo-prirody.com/uploads/posts/2021-08/1628244303_29-p-amerikanskii-bobteil-koshka-foto-29.jpg',
    price: 640,
  },
  {
    id: 6,
    breed: 'American bobtail',
    homeCity: 'Brest',
    name: 'Murzik',
    imageSrc: 'https://i.pinimg.com/originals/b8/81/34/b881345b242f370c103f9eeb2dd97554.jpg',
    price: 680,
  },
  {
    id: 7,
    breed: 'Balinese',
    homeCity: 'Vilnius',
    name: 'Nona',
    imageSrc: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Old-Style_Balinese_Cat.png',
    price: 400,
  },
  {
    id: 8,
    breed: 'Balinese',
    homeCity: 'Tokio',
    name: 'Minamoto',
    imageSrc: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Ghislaine_6028.jpg',
    price: 410,
  },
  {
    id: 9,
    breed: 'Birman',
    homeCity: 'Tokio',
    name: 'Hasimoto',
    imageSrc: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Birman2.jpg',
    price: 420,
  },
  {
    id: 10,
    breed: 'Birman',
    homeCity: 'Beijing',
    name: 'Luiza',
    imageSrc: 'https://upload.wikimedia.org/wikipedia/commons/0/06/Birmanstrofe.jpg',
    price: 480,
  },
  {
    id: 11,
    breed: 'Bengal',
    homeCity: 'Prague',
    name: 'Lola',
    imageSrc:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Best_Stalk.jpg/1280px-Best_Stalk.jpg',
    price: 500,
  },
  {
    id: 12,
    breed: 'Bengal',
    homeCity: 'Milan',
    name: 'Zephyr',
    imageSrc:
      'https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/Catbengalinbedresting.jpg/1024px-Catbengalinbedresting.jpg',
    price: 600,
  },
  {
    id: 13,
    breed: 'Cornish rex',
    homeCity: 'New York',
    name: 'Star',
    imageSrc: 'https://house-animals.ru/sites/default/files/media/user-1/cornish-rex-cat.jpg',
    price: 700,
  },
  {
    id: 14,
    breed: 'Cornish rex',
    homeCity: 'Los Angeles',
    name: 'Moona',
    imageSrc: 'https://i.pinimg.com/originals/90/8d/12/908d123c4a38f8e8bad5eece1968654a.jpg',
    price: 750,
  },
  {
    id: 15,
    breed: 'Persian',
    homeCity: 'Chicago',
    name: 'Lollipop',
    imageSrc: 'https://kot-pes.com/wp-content/uploads/2019/01/post_5c47684e9a452.jpg',
    price: 400,
  },
  {
    id: 16,
    breed: 'Persian',
    homeCity: 'Istanbul',
    name: 'CookieCat',
    imageSrc: 'https://kot-pes.com/wp-content/uploads/2019/02/post_5c48b6275c49e.jpg',
    price: 500,
  },
];
